- Jenkinsfile
- e2e-tests/affinity/compare/deployment_some-name-backrest-shared-repo.yml
- e2e-tests/affinity/compare/deployment_some-name-disabled-backrest-shared-repo.yml
- e2e-tests/affinity/compare/deployment_some-name-disabled.yml
- e2e-tests/affinity/compare/deployment_some-name-required-backrest-shared-repo.yml
- e2e-tests/affinity/compare/deployment_some-name-required.yml
- e2e-tests/affinity/compare/deployment_some-name.yml
- e2e-tests/affinity/run
- e2e-tests/functions
* K8SPG-38 Affinity test
* K8SPG-38 Fixing linter buzz
* K8SPG-38 Fixing linter buzz vol.2
> K8SPG-38 Affinity test (#51)

- e2e-tests/recreate/run
Now test is checking dynamic configuration changes
> K8SPG-38 Recreate test enhancement

- source/backups.rst
* add example how to delete backup object
> K8SPG-110 delete unneeded link from GCS backup section to s3 options

- e2e-tests/upgrade/run
Previous approach ignored explicitly stated images
Now we are taking them into consideration
> K8SPG-38 Upgrade test enhancement

- deploy/cr.yaml
- e2e-tests/affinity/compare/deployment_some-name-disabled-oc.yml
- e2e-tests/functions
- e2e-tests/init-deploy/compare/deployment_some-name-pgbouncer-oc.yml
- e2e-tests/init-deploy/compare/deployment_some-name-pgbouncer.yml
- e2e-tests/init-deploy/compare/service_postgres-operator.yml
- e2e-tests/init-deploy/compare/service_some-name-backrest-shared-repo.yml
- e2e-tests/init-deploy/compare/service_some-name-pgbouncer.yml
- e2e-tests/init-deploy/compare/service_some-name.yml
- e2e-tests/recreate/compare/deployment_some-name-pgbouncer-oc.yml
- e2e-tests/recreate/compare/deployment_some-name-pgbouncer.yml
- e2e-tests/recreate/compare/service_some-name-pgbouncer.yml
Since EKS does not provide any annotations for service objects
we are to remove them from compare files
> K8SPG-145 Remove service annotations

- deploy/cr.yaml
1. this is yet another place where user would need to change cluster1 to another name
2. I would love operator to generate the secret by default <clusterName>-users
> K8SPG-113 comment custom secret

- README.md
add helm
add raw files installation via kubectl
> CLOUD-677 Update README.md - pg helm

- source/TLS.rst
Fix formatting errors for https://jira.percona.com/browse/K8SPXC-968
> K8PXC-968 fix formatting errors

- deploy/cr.yaml
* Enable smart update by default
* Ensure resources for all components are there (requests are set for both mem and cpu, limits are commented)
> K8SPG-167 - Update cr.yaml

- deploy/cr-minimal.yaml
Deploy minimal cluster.
@fiowro please update the docs so that we have it reflected in minikube doc the same way as we do for PXC and MongoDB.
> K8SPG-142 - add cr-minimal.yaml

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/linters/go.mod
- .github/workflows/reviewdog.yml
- .github/workflows/scan.yml
- build/postgres-operator/Dockerfile
- e2e-tests/build
- e2e-tests/vars.sh
- go.mod
- go.sum
- installers/olm/README.md
- internal/upgradecheck/http.go
* add CODEOWNERS file
* add scan for CVE
* add dep bot
* update 'golang.org/x/net' go module to fix CVE
> K8SPG-257 create build script and update Dockerfile

- Jenkinsfile
- e2e-tests/functions
- e2e-tests/tests/demand-backup/00-assert.yaml
- e2e-tests/tests/demand-backup/00-deploy-operator.yaml
- e2e-tests/tests/demand-backup/01-assert.yaml
- e2e-tests/tests/demand-backup/01-create-cluster.yaml
- e2e-tests/tests/demand-backup/02-write-data.yaml
- e2e-tests/tests/demand-backup/03-assert.yaml
- e2e-tests/tests/demand-backup/03-read-from-primary.yaml
- e2e-tests/tests/demand-backup/04-assert.yaml
- e2e-tests/tests/demand-backup/04-issue-backup.yaml
- e2e-tests/tests/demand-backup/05-add-more-data.yaml
- e2e-tests/tests/demand-backup/05-assert.yaml
- e2e-tests/tests/demand-backup/06-assert.yaml
- e2e-tests/tests/demand-backup/06-issue-restore.yaml
- e2e-tests/tests/demand-backup/07-assert.yaml
- e2e-tests/tests/demand-backup/07-verify-restored-data.yaml
- e2e-tests/vars.sh
Simple version of test with s3 only backup storage for the beginning
> K8SPG-258 E2E demand-backup test

- e2e-tests/tests/monitoring/02-assert.yaml
- internal/controller/postgrescluster/controller.go
- internal/controller/postgrescluster/postgres.go
- internal/pgstatmonitor/pgstatmonitor.go
- internal/postgres/hba.go
- percona/pmm/pmm.go
> fix pg_stat_monitor

- percona/controllers/pgcluster/pgcluster.go
https://github.com/percona/percona-postgresql-operator/pull/301 had to be rebased So, doing this here
thanks to @TimTalent
> INFRA-699: Pass PerconaPGCluster PGPrimary Annotations to Pgcluster

- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/operator.yaml
- percona/version/version.go
> RM-1151 Set versions main again

- .github/workflows/test.yml
- internal/pgbackrest/config_test.go
- internal/pgbouncer/config_test.go
- internal/pki/pki_test.go
- internal/postgres/config_test.go
- internal/postgres/hba_test.go
- internal/postgres/reconcile_test.go
https://jira.percona.com/browse/K8SPG-273
PR adds a GitHub action to run unit/integration tests on PRs.
Couple of tests are skipped since they are broken and will be fixed with https://jira.percona.com/browse/K8SPG-274
> K8SPG273: Run unit tests on PR

- Jenkinsfile
> CLOUD-769 Freeze kuttl version during release cycle

- e2e-tests/build
> K8SPG-294 Simplify build script run on Apple M1

- e2e-tests/init-deploy/compare/deployment_some-namealways-oc.yml
- e2e-tests/init-deploy/compare/deployment_some-namealways.yml
- e2e-tests/init-deploy/compare/deployment_some-namenotpresent-oc.yml
- e2e-tests/init-deploy/compare/deployment_some-namenotpresent.yml
- percona/controllers/pmm/pmm.go
> K8SPG-286 Adding actual tls certificats to pmm client

- build/pgo-scheduler/Dockerfile
- cmd/pgo-scheduler/scheduler/pgbackrest.go
- cmd/pgo-scheduler/scheduler/scheduler.go
- cmd/pgo-scheduler/scheduler/tasks.go
- cmd/pgo-scheduler/scheduler/types.go
- e2e-tests/affinity/compare/job_backrest-backup-some-name-disabled.yml
- e2e-tests/affinity/compare/job_backrest-backup-some-name-required.yml
- e2e-tests/affinity/compare/job_backrest-backup-some-name.yml
- e2e-tests/affinity/run
- e2e-tests/functions
- internal/config/labels.go
- internal/operator/backrest/backup.go
- percona/controllers/deployment/deployment.go
- percona/controllers/pgbouncer/pgbouncer.go
- percona/controllers/pgc/schedule.go
- percona/controllers/pgcluster/pgcluster.go
- percona/controllers/template/template.go
- percona/templates/backrest-job.json
Updating affinity does nothing.
> K8SPG-269: Fix updating cluster deployments on affinity update

- e2e-tests/demand-backup/run
- e2e-tests/functions
- e2e-tests/scheduled-backup/run
> K8SPG-294 Wait for complete cluster removal

- percona/controllers/perconapgcluster_controller.go
Handle `spec.shutdown` field properly.
**Checklist:**
https://jira.percona.com/browse/K8SPG-298
> K8SPG-298: Map shutdown field

- deploy/cr-minimal.yaml
- deploy/cr.yaml
- deploy/operator.yaml
> K8SPG-294 Set release 1.4.0 image tags

- .github/workflows/test.yml
- .gitignore
- Makefile
- go.mod
- go.sum
- percona/controllers/pgcluster_test.go
- percona/controllers/suite_test.go
Setup envtest/gingko test suite.
**Checklist:**
https://jira.percona.com/browse/K8SPG-274
> K8SPG-274: EnvTest setup

- cmd/postgres-operator/main.go
- percona/controller/pgbackup/controller.go
- percona/controller/pgcluster/contoller_test.go
- percona/controller/pgcluster/controller.go
- percona/controller/pgcluster/suite_test.go
- percona/controller/pgrestore/controller.go
- percona/controller/utils.go
[![K8SPG-295](https://badgen.net/badge/JIRA/K8SPG-295/green)](https://jira.percona.com/browse/K8SPG-295) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Refactor `percona/controller`.
**Checklist:**
> K8SPG-295: Refactor percona/controller

- Makefile
- build/crd/percona/generated/pg.percona.com_perconapgbackups.yaml
- build/crd/percona/generated/pg.percona.com_perconapgclusters.yaml
- build/crd/percona/generated/pg.percona.com_perconapgrestores.yaml
- config/crd/bases/pg.percona.com_perconapgclusters.yaml
- deploy/bundle.yaml
- deploy/crd.yaml
- pkg/apis/pg.percona.com/v2beta1/perconapgbackup_types.go
- pkg/apis/pg.percona.com/v2beta1/perconapgcluster_types.go
- pkg/apis/pg.percona.com/v2beta1/perconapgrestore_types.go
[![K8SPG-331](https://badgen.net/badge/JIRA/K8SPG-331/green)](https://jira.percona.com/browse/K8SPG-331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We want short name for our CRD.
**Solution:**
We added `pg` as short name.
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-331: Add short name to CRD

- README.md
[![K8SPG-337](https://badgen.net/badge/JIRA/K8SPG-337/green)](https://jira.percona.com/browse/K8SPG-337) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* add shields to README
* change README to have consistency between all our operators
> K8SPG-337 update README

- .github/linters/go.mod
- .github/workflows/reviewdog.yml
- .github/workflows/test.yml
- Jenkinsfile
- build/postgres-operator/Dockerfile
- go.mod
[![K8SPG-338](https://badgen.net/badge/JIRA/K8SPG-338/green)](https://jira.percona.com/browse/K8SPG-338) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Solution:
Update got version to 1.20
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-338 update go version to 1.20

- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/operator.yaml
[![K8SPG-352](https://badgen.net/badge/JIRA/K8SPG-352/green)](https://jira.percona.com/browse/K8SPG-352) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Post release changes.
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-352 post release changes

- installers/olm/Makefile
[![K8SPG-356](https://badgen.net/badge/JIRA/K8SPG-356/green)](https://jira.percona.com/browse/K8SPG-356) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Fix k8s version and platform
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-356 fix makefile

- Jenkinsfile
[![CLOUD-793](https://badgen.net/badge/JIRA/CLOUD-793/green)](https://jira.percona.com/browse/CLOUD-793) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Different tool versions can cause issues with the tests.*
**Solution:**
*Fix version.*
**CHECKLIST**
---
**Jira**
**Tests**
> CLOUD-793 - Set fixed version of jq and yq in Jenkinsfile

- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
[![K8SPG-354](https://badgen.net/badge/JIRA/K8SPG-354/green)](https://jira.percona.com/browse/K8SPG-354) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Post release changes
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-354 post release changes

- .github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> CLOUD-727 set day and time for dependabot

- e2e-tests/functions
[![CLOUD-789](https://badgen.net/badge/JIRA/CLOUD-789/green)](https://jira.percona.com/browse/CLOUD-789) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> CLOUD-789 - add test to check password leaks in the logs

- .github/CODEOWNERS
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Update codeowners for github

- README.md
[![K8SPG-444](https://badgen.net/badge/JIRA/K8SPG-444/green)](https://jira.percona.com/browse/K8SPG-444) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-444 remove tech preview note from README

- Jenkinsfile
- Makefile
- build/crd/crunchy/generated/postgres-operator.crunchydata.com_pgupgrades.yaml
- build/crd/crunchy/generated/postgres-operator.crunchydata.com_postgresclusters.yaml
- build/crd/percona/generated/pgv2.percona.com_perconapgclusters.yaml
- config/crd/bases/pgv2.percona.com_perconapgclusters.yaml
- config/crd/bases/postgres-operator.crunchydata.com_pgupgrades.yaml
- config/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
- docs/content/references/crd.md
- e2e-tests/vars.sh
- pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
- pkg/apis/postgres-operator.crunchydata.com/v1beta1/postgrescluster_types.go
[![K8SPG-434](https://badgen.net/badge/JIRA/K8SPG-434/green)](https://jira.percona.com/browse/K8SPG-434) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Add PG 16 support
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-434 add PG 16 support

- e2e-tests/functions
[![K8SPG-391](https://badgen.net/badge/JIRA/K8SPG-391/green)](https://jira.percona.com/browse/K8SPG-391) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-391 add param for openshift

- percona/controller/pgcluster/controller_test.go
- pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-455](https://badgen.net/badge/JIRA/K8SPG-455/green)](https://jira.percona.com/browse/K8SPG-455) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Some features of Crunchy works with annotations. When user annotates the PerconaPGCluster CR, our controller passes the annotations to Crunchy CR. If an annotation uses `pgv2.percona.com` prefix, we need to convert it to `postgres-operator.crunchydata.com` before passing.
**Solution:**
Convert.
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-455: Convert Percona annotations to Crunchy

- deploy/cr.yaml
[![K8SPG-458](https://badgen.net/badge/JIRA/K8SPG-458/green)](https://jira.percona.com/browse/K8SPG-458) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
There's no affinity configuration by default.
**Solution:**
Configure affinity settings in default cr.yaml.
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-458: Add default affinity settings

- Jenkinsfile
[![CLOUD-822](https://badgen.net/badge/JIRA/CLOUD-822/green)](https://jira.percona.com/browse/CLOUD-822) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPG-471 Add data-migration-gcs test to Jenkinsfile

- e2e-tests/init-deploy/compare/deployment_some-namealways-oc.yml
- e2e-tests/init-deploy/compare/deployment_some-namealways.yml
- e2e-tests/init-deploy/compare/deployment_some-namenotpresent-oc.yml
- e2e-tests/init-deploy/compare/deployment_some-namenotpresent.yml
- e2e-tests/monitoring/compare/deployment_some-name-oc.yml
- e2e-tests/monitoring/compare/deployment_some-name.yml
- percona/controllers/pmm/pmm.go
[![K8SPG-482](https://badgen.net/badge/JIRA/K8SPG-482/green)](https://jira.percona.com/browse/K8SPG-482) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Problem:
Failed to start Agent: mkdir /usr/local/percona/pmm2/tmp: permission denied
Solution:
Set "PMM_AGENT_PATHS_TEMPDIR" to "/tmp"
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-482: Fix tmp permission error on openshift

- deploy/operator.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Update pgo_image_tag to 1.5.0

- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-358 Update Percona PostgreSQL operator image version to 2.3.0

- e2e-tests/functions
- e2e-tests/tests/telemetry-transfer/00-deploy-version-service.yaml
- e2e-tests/tests/telemetry-transfer/03-assert.yaml
- e2e-tests/tests/telemetry-transfer/03-verify-transferred-default.yaml
---
**Change:**
*Telemetry was disabled, but this test expects it to be enabled.
Also now we specify dynamic latest image for version service.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPG-358 - Fix telemetry-transfer test

- e2e-tests/tests/upgrade-minor/01-create-cluster.yaml
- e2e-tests/tests/upgrade-minor/05-upgrade-cluster.yaml
---
*`upgrade-minor` test did not set `spec.postgresVersion` correctly*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-358]: https://perconadev.atlassian.net/browse/K8SPG-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-358 - Fix upgrade-minor test

- .github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-727]: https://perconadev.atlassian.net/browse/CLOUD-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> CLOUD-727 we can set day only for weekly interval

- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- e2e-tests/tests/upgrade-minor/01-assert.yaml
- e2e-tests/tests/upgrade-minor/04-assert.yaml
- e2e-tests/tests/upgrade-minor/05-assert.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-358]: https://perconadev.atlassian.net/browse/K8SPG-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-358 New version code preparations

- percona/controller/pgcluster/controller.go
[![K8SPG-496](https://badgen.net/badge/JIRA/K8SPG-496/green)](https://jira.percona.com/browse/K8SPG-496) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-496
---
**Problem:**
*If the cluster is set to `pause: true` while the backup is running, the cluster will not pause when the backup is complete.*
**Cause:**
*Reconcile doesn't trigger after backup completion.*
**Solution:**
*We should add a new watch function that will trigger a reconcile when the `PerconaPGBackup` resource is updated..*
**CHECKLIST**
---
**Jira**
**Tests** …
> K8SPG-496: trigger reconcile on `PerconaPGBackup` update

- build/postgres-operator/Dockerfile
- e2e-tests/build
[![K8SPG-451](https://badgen.net/badge/JIRA/K8SPG-451/green)](https://jira.percona.com/browse/K8SPG-451) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Jenkins job PR  https://github.com/Percona-Lab/jenkins-pipelines/pull/2563, test run https://cloud.cd.percona.com/view/PG/job/pgo-v2-docker-build/3709
[K8SPG-451]: https://perconadev.atlassian.net/browse/K8SPG-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-451 improve multi architecture builds

- deploy/cr.yaml
[![K8SPG-562](https://badgen.net/badge/JIRA/K8SPG-562/green)](https://jira.percona.com/browse/K8SPG-562) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-562]: https://perconadev.atlassian.net/browse/K8SPG-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-562 - Add example for incremental backup schedule in cr.yaml

- deploy/cr.yaml
[![K8SPG-573](https://badgen.net/badge/JIRA/K8SPG-573/green)](https://jira.percona.com/browse/K8SPG-573) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-573]: https://perconadev.atlassian.net/browse/K8SPG-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-573 - Add example for storageClassName in cr.yaml

- percona/controller/pgcluster/status.go
[![K8SPG-510](https://badgen.net/badge/JIRA/K8SPG-510/green)](https://jira.percona.com/browse/K8SPG-510) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The problem was that we jumped from ready to paused without stopping step. now it should work correctly. 
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-510]: …
> K8SPG-510 update cluster status

- Makefile
- config/crd/kustomization.yaml
- deploy/bundle.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
[![K8SPG-549](https://badgen.net/badge/JIRA/K8SPG-549/green)](https://jira.percona.com/browse/K8SPG-549) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-549
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-549]: https://perconadev.atlassian.net/browse/K8SPG-549?atlOrigin=eyJpIjoiNWRkNTlj …
> K8SPG-549: fix crd generation

- e2e-tests/run-minikube.csv
- e2e-tests/run-pr.csv
- e2e-tests/run-release.csv
- e2e-tests/tests/one-pod/00-assert.yaml
- e2e-tests/tests/one-pod/00-deploy-operator.yaml
- e2e-tests/tests/one-pod/01-assert.yaml
- e2e-tests/tests/one-pod/01-create-cluster.yaml
- e2e-tests/tests/one-pod/02-write-data.yaml
- e2e-tests/tests/one-pod/03-assert.yaml
- e2e-tests/tests/one-pod/03-read-from-primary.yaml
- e2e-tests/tests/one-pod/04-assert.yaml
- e2e-tests/tests/one-pod/04-create-backup.yaml
- e2e-tests/tests/one-pod/05-check-pgbackrest-info.yaml
- e2e-tests/tests/one-pod/06-delete-data.yaml
- e2e-tests/tests/one-pod/07-assert.yaml
- e2e-tests/tests/one-pod/07-create-restore.yaml
- e2e-tests/tests/one-pod/08-assert.yaml
- e2e-tests/tests/one-pod/08-verify-restored-data.yaml
- e2e-tests/tests/one-pod/09-check-pgbackup-job.yaml
- e2e-tests/tests/one-pod/99-remove-cluster-gracefully.yaml
[![K8SPG-303](https://badgen.net/badge/JIRA/K8SPG-303/green)](https://jira.percona.com/browse/K8SPG-303) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Add one-pod test which tries to do backup and restore with 1 database pod and 1 proxy pod.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-509]: https://perconadev.atlassian.net/browse/K8SPG-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[K8SPG-303]: https://perconadev.atlassian.net/browse/K8SPG-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
> K8SPG-303 - Add one-pod test

- e2e-tests/run-minikube.csv
- e2e-tests/run-pr.csv
- e2e-tests/run-release.csv
- e2e-tests/tests/upgrade-consistency/00-assert.yaml
- e2e-tests/tests/upgrade-consistency/00-deploy-operator.yaml
- e2e-tests/tests/upgrade-consistency/01-assert.yaml
- e2e-tests/tests/upgrade-consistency/01-create-cluster.yaml
- e2e-tests/tests/upgrade-consistency/02-assert.yaml
- e2e-tests/tests/upgrade-consistency/02-patch-cluster.yaml
- e2e-tests/tests/upgrade-consistency/03-assert.yaml
- e2e-tests/tests/upgrade-consistency/03-patch-cluster.yaml
- e2e-tests/tests/upgrade-consistency/04-assert.yaml
- e2e-tests/tests/upgrade-consistency/04-patch-cluster.yaml
- e2e-tests/tests/upgrade-consistency/99-remove-cluster-gracefully.yaml
[![K8SPG-303](https://badgen.net/badge/JIRA/K8SPG-303/green)](https://jira.percona.com/browse/K8SPG-303) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Add upgrade-consistency test
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-303]: https://perconadev.atlassian.net/browse/K8SPG-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-303 - Add upgrade-consistency test

- deploy/cr.yaml
[![K8SPG-492](https://badgen.net/badge/JIRA/K8SPG-492/green)](https://jira.percona.com/browse/K8SPG-492) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*repo host will not work if tolerations are not set for needed taints, so let's add an example here as well*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-492]: https://perconadev.atlassian.net/browse/K8SPG-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-492 - Add example for repoHost tolerations

- Makefile
- config/bundle/kustomization.yaml
- config/cw-bundle/kustomization.yaml
- config/manager/cluster/kustomization.yaml
- config/manager/namespace/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- deploy/upgrade.yaml
[![K8SPG-597](https://badgen.net/badge/JIRA/K8SPG-597/green)](https://jira.percona.com/browse/K8SPG-597) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-597]: https://perconadev.atlassian.net/browse/K8SPG-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-597 Update images and versions for 2.4.0 release

- Jenkinsfile
[![CLOUD-850](https://badgen.net/badge/JIRA/CLOUD-850/green)](https://jira.percona.com/browse/CLOUD-850) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-850]: https://perconadev.atlassian.net/browse/CLOUD-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> CLOUD-850 - Update kuttl to v0.17.0

- config/bundle/kustomization.yaml
- config/cw-bundle/kustomization.yaml
- config/manager/cluster/kustomization.yaml
- config/manager/namespace/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- deploy/upgrade.yaml
- pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-597](https://badgen.net/badge/JIRA/K8SPG-597/green)](https://jira.percona.com/browse/K8SPG-597) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-597]: https://perconadev.atlassian.net/browse/K8SPG-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-597 post-release Update images and versions

- Jenkinsfile
- config/bundle/kustomization.yaml
- config/cw-bundle/kustomization.yaml
- config/manager/cluster/kustomization.yaml
- config/manager/namespace/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- deploy/upgrade.yaml
- pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-617](https://badgen.net/badge/JIRA/K8SPG-617/green)](https://jira.percona.com/browse/K8SPG-617) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-617]: https://perconadev.atlassian.net/browse/K8SPG-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-617 Update images and versions for 2.4.1 release

- deploy/upgrade.yaml
[![K8SPG-598](https://badgen.net/badge/JIRA/K8SPG-598/green)](https://jira.percona.com/browse/K8SPG-598) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Updated example with newly added fields.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-598]: https://perconadev.atlassian.net/browse/K8SPG-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-598: Add fields to major upgrade example

- percona/controller/pgcluster/controller.go
- percona/controller/pgcluster/controller_test.go
[![K8SPG-555](https://badgen.net/badge/JIRA/K8SPG-555/green)](https://jira.percona.com/browse/K8SPG-555) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-555
---
This PR adds a unit-test for https://github.com/percona/percona-postgresql-operator/pull/906
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-555]: https://perconadev.atlassian.net/browse/K8SPG-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-555: add test

- Makefile
- config/bundle/kustomization.yaml
- config/cw-bundle/kustomization.yaml
- config/manager/cluster/kustomization.yaml
- config/manager/namespace/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- deploy/upgrade.yaml
- pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-604](https://badgen.net/badge/JIRA/K8SPG-604/green)](https://jira.percona.com/browse/K8SPG-604) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-604]: https://perconadev.atlassian.net/browse/K8SPG-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-604 - Update images and versions post-release

- README.md
[![CLOUD-878](https://badgen.net/badge/JIRA/CLOUD-878/green)](https://jira.percona.com/browse/CLOUD-878) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
minor fixes and links to website and forum
[CLOUD-878]: https://perconadev.atlassian.net/browse/CLOUD-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLOUD-878] minor fixes and links from README

- README.md
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Fix broken link to CrunchyData/postgres-operator

- config/bundle/kustomization.yaml
- config/cw-bundle/kustomization.yaml
- config/manager/cluster/kustomization.yaml
- config/manager/namespace/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- deploy/upgrade.yaml
- percona/controller/testdata/sidecar-resources-cr.yaml
- pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-735](https://badgen.net/badge/JIRA/K8SPG-735/green)](https://jira.percona.com/browse/K8SPG-735) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-735]: https://perconadev.atlassian.net/browse/K8SPG-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-735: Update versions for 2.5.1 release

- e2e-tests/functions
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Increase delete timeout

- Makefile
- deploy/cr.yaml
- deploy/upgrade.yaml
- e2e-tests/conf/client.yaml
- e2e-tests/functions
- e2e-tests/release_versions
- e2e-tests/vars.sh
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Update default db to PG16

- config/bundle/kustomization.yaml
- config/cw-bundle/kustomization.yaml
- config/manager/cluster/kustomization.yaml
- config/manager/namespace/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- deploy/upgrade.yaml
- e2e-tests/tests/init-deploy/05-assert.yaml
- e2e-tests/tests/upgrade-consistency/01-assert.yaml
- e2e-tests/tests/upgrade-consistency/01-create-cluster.yaml
- e2e-tests/tests/upgrade-consistency/02-assert.yaml
- e2e-tests/tests/upgrade-consistency/02-patch-cluster.yaml
- e2e-tests/tests/upgrade-consistency/03-assert.yaml
- e2e-tests/tests/upgrade-consistency/03-patch-cluster.yaml
- e2e-tests/tests/upgrade-minor/05-assert.yaml
- e2e-tests/tests/upgrade-minor/06-assert.yaml
- internal/postgres/reconcile_test.go
- percona/controller/testdata/sidecar-resources-cr.yaml
- pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-651](https://badgen.net/badge/JIRA/K8SPG-651/green)](https://jira.percona.com/browse/K8SPG-651) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-651]: https://perconadev.atlassian.net/browse/K8SPG-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-651 - Update images and versions post-release

- build/crd/percona/generated/pgv2.percona.com_perconapgclusters.yaml
- config/crd/bases/pgv2.percona.com_perconapgclusters.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
- e2e-tests/functions
- e2e-tests/tests/monitoring-pmm3/03-assert.yaml
- e2e-tests/tests/monitoring/03-assert.yaml
- percona/pmm/pmm.go
- percona/pmm/pmm_test.go
- pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-750](https://badgen.net/badge/JIRA/K8SPG-750/green)](https://jira.percona.com/browse/K8SPG-750) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Allow to customize cluster name for pmm and add it to params.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-750]: https://perconadev.atlassian.net/browse/K8SPG-750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-750 add cluster name to pmm

- deploy/cr.yaml
[![K8SPG-753](https://badgen.net/badge/JIRA/K8SPG-753/green)](https://jira.percona.com/browse/K8SPG-753) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Helm PR: https://github.com/percona/percona-helm-charts/pull/518
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-753]: https://perconadev.atlassian.net/browse/K8SPG-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPG-753: Add pg_stat_statements into cr.yaml

- deploy/upgrade.yaml
[![K8SPG-812](https://badgen.net/badge/JIRA/K8SPG-812/green)](https://jira.percona.com/browse/K8SPG-812) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-812]: https://perconadev.atlassian.net/browse/K8SPG-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-812 fix upgrade image

- Makefile
- config/bundle/kustomization.yaml
- config/cw-bundle/kustomization.yaml
- config/manager/cluster/kustomization.yaml
- config/manager/namespace/kustomization.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- deploy/upgrade.yaml
- e2e-tests/functions
- e2e-tests/release_versions
[![K8SPG-818](https://badgen.net/badge/JIRA/K8SPG-818/green)](https://jira.percona.com/browse/K8SPG-818) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-818]: https://perconadev.atlassian.net/browse/K8SPG-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> K8SPG-818 Update versions for 2.7.0 release

- e2e-tests/functions
[![K8SPG-719](https://badgen.net/badge/JIRA/K8SPG-719/green)](https://jira.percona.com/browse/K8SPG-719) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Errors observed:
>  kl monitoring-0
> + [[ 1000 != 1000 ]]
> + '[' '!' -f /pmmdata/app-init ']'
> + mkdir -p /pmmdata
> + rsync -a --owner=1000 /srv/prometheus/data/ /pmmdata/prometheus-data/
> rsync: [sender] change_dir "/srv/prometheus/data" failed: No such file or directory (2)
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1327) [sender=3.2.5] …
> K8SPG-719 fixes on the deploy_pmm3_server for openshift

- e2e-tests/tests/demand-backup/16-check-password-leak.yaml
- e2e-tests/tests/demand-backup/23-check-password-leak.yaml
- e2e-tests/tests/init-deploy/04-check-password-leak.yaml
- e2e-tests/tests/monitoring-pmm3/07-check-password-leak.yaml
- e2e-tests/tests/monitoring/07-check-password-leak.yaml
- e2e-tests/tests/tablespaces/06-check-password-leak.yaml
- e2e-tests/tests/tablespaces/10-check-password-leak.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> Disable pass check in tests
