percona/percona-postgresql-operator

deploy/cr.yaml
Since storageclass name is used as is, we need to
preserve the usage of default system storageclass
=> K8SPG-90 Remove default storageclass from CR

e2e-tests/data-migration-gcs/run
Since we need to test data migration on both
version, let's use it for the upstream cluster too
=> K8SPG-90 Support PostgreSQL 12 and 13

build/pgo-apiserver/Dockerfile, build/pgo-deployer/Dockerfile, build/pgo-event/Dockerfile, build/pgo-rmdata/Dockerfile, build/pgo-scheduler/Dockerfile, build/postgres-operator/Dockerfile
As it turns out, RedHat can't certify ubi based image
without short 'ubi8' alias stated in Dockerfiles
=> K8SPG-86 Add short alias for source image

e2e-tests/functions, e2e-tests/upgrade/run
TLS options included in pgbouncer template only if
spec.pgBouncer.tlsSecret, spec.sslCA and spec.sslSecretName is not
empty. But just updating these fields is not enough, you need to disable
pgbouncer and enable it back by setting replicas to 0 and 1.
Unfortunately deleting the deployment object doesn't work since the
operator doesn't re-create it.
=> K8SPG-195: Fix pgbouncer TLS error

deploy/operator.yaml
Explicitly stated option does not let operator to manage
pod FSgroup flawlessly
=> K8SPG-204 Enable Openshift detection by default

internal/apiserver/upgradeservice/upgradeimpl.go, internal/apiserver/upgradeservice/upgradeimpl_test.go
The upgradeTagValid was originally checking tags as strings
which led to 12.9=>12.10 upgrades being rejected as invalid.
This changes that validator to check certain parts of the tag
as ints rather than strings, and adds a unit test.
Issue [sc-14575]
=> Adjust upgrade valid check (#3223)

e2e-tests/functions
In order to get the smooth operation of TLS related part of
demand-backup test cert-manager has to be updated
Also, openshift does not let minio native bucket creation job finish, so
switching back to the explicit awscli call with CA injected
=> K8SPG-238 Minor test update

e2e-tests/functions
Since storage-provisioner is no longer in Beta in 1.24 we need to
adjust our framework accordingly
=> K8SPG-238 1.24 compatibility for test infra

e2e-tests/functions
In order to get rid of unneccessary fuzz in our analitycs on
check.percona.com side, we are to disable the setting by default
=> K8SPG-239 Disable telemetry transfer by default in e2e-testing

e2e-tests/tests/monitoring/01-assert.yaml, e2e-tests/tests/monitoring/03-check-metrics.yaml
It turns out that pmm-server treats a node as entity with namespace as prefix inside a name
=> K8SPG-265 A minor fix for monitoring test

Jenkinsfile, e2e-tests/kuttl.yaml, e2e-tests/tests/demand-backup/08-remove-cluster-gracefully.yaml, e2e-tests/tests/init-deploy/04-remove-cluster-gracefully.yaml, e2e-tests/tests/monitoring/04-remove-cluster-gracefully.yaml, e2e-tests/tests/start-from-backup/03-remove-cluster-gracefully.yaml
Since the operator does not support the legit way for removing finalizer from the calculated cluster object, let's remove the object gracefully as it's supposed to be deleted by user.
=> CLOUD-765 Gracefully remove cluster object for namespace deletion

.github/workflows/test.yml, internal/pgbackrest/config_test.go, internal/pgbouncer/config_test.go, internal/pki/pki_test.go, internal/postgres/config_test.go, internal/postgres/reconcile_test.go
https://jira.percona.com/browse/K8SPG-274
Update test github action to use Ubuntu 20.04 and updated `TestInstancePod/WithCustomSidecarContainer/SidecarNotEnabled` with explicitly disabling sidecars feature gate.
**Checklist:**
=> K8SPG-274: Fix tests

config/default/kustomization.yaml, installers/olm/generate.sh
[![K8SPG-316](https://badgen.net/badge/JIRA/K8SPG-316/green)](https://jira.percona.com/browse/K8SPG-316) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
OLM installations don't work because of missing permissions in cluster scope.
**Cause:**
Operator runs in cluster wide mode if `PGO_TARGET_NAMESPACE` env variable is empty. 
**Solution:**
Ensure `PGO_TARGET_NAMESPACE` exists in operator deployment in CSV and use proper role.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-316: Run operator in namespace scope with OLM

percona/controller/pgcluster/controller.go, percona/controller/pgcluster/controller_test.go, percona/controller/pgcluster/status.go, percona/k8s/util.go, pkg/apis/pg.percona.com/v2beta1/perconapgcluster_types.go
[![K8SPG-334](https://badgen.net/badge/JIRA/K8SPG-334/green)](https://jira.percona.com/browse/K8SPG-334) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
1. postgres-exporter doesn't work with passwords with commas.
2. reconciliation errors if user defines `monitor` user in CR.
3. we need to restart PG pods if PMM API key is rotated.
4. CR status is ready right after cluster is created and then becomes initializing.
**Solution:**
1. Use only alphanumeric characters for monitor user.
2. Ignore `monitor` user in CR.
3. We watch for changes in PMM …
=> K8SPG-334: PMM fixes and improvements

e2e-tests/run-minikube.csv, e2e-tests/run-release.csv, e2e-tests/tests/demand-backup/01-assert.yaml, e2e-tests/tests/demand-backup/04-assert.yaml, e2e-tests/tests/scheduled-backup/05-assert.yaml, e2e-tests/tests/start-from-backup/01-assert.yaml
[![K8SPG-302](https://badgen.net/badge/JIRA/K8SPG-302/green)](https://jira.percona.com/browse/K8SPG-302) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Change:**
*Some timeouts were too low for minikube and this also adds `run-minikube.csv` file with the list of tests which are supported on minikube and which will be used from parametrized pipeline.
`monitoring` test was not added because it is using LoadBalancer which minikube doesn't support.*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-302 - Update tests for minikube and add run-minikube.csv

.gitignore
[![K8SPG-397](https://badgen.net/badge/JIRA/K8SPG-397/green)](https://jira.percona.com/browse/K8SPG-397) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
When I clone the repo and run some test with kuttl framework, two local file are created: `kubeconfig` and `gke_gcloud_auth_plugin_cache` which are needed for the proper operation of the `kubectl` and `gcloud` commands. However, those files are being listed as `Untracked files` by git, but they are not meant to be committed in the repo.
**Solution:**
I added them in the `.gitignore` file. …
=> K8SPG-397 Added gke_gcloud_auth_plugin_cache and kubeconfig in .gitignore

Jenkinsfile, internal/controller/pod/inithandler.go, internal/operator/cluster/clusterlogic.go
[![K8SPG-420](https://badgen.net/badge/JIRA/K8SPG-420/green)](https://jira.percona.com/browse/K8SPG-420) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
There are two problems after unpausing the cluster:
1. Replica deployments are not scaled up
2. On certain control planes (i.e. k3d v5.5.2) backrest repo pods scaled up incorrectly
**Cause:**
1.  An implementation problem. Crunchy controller didn't implement scaling up replicas after starting up from shutdown.
2. A bug. If pgbouncer deployment is processed before backrest deployment, the bug …
=> K8SPG-420: Fix unpause problems

Jenkinsfile, Makefile, e2e-tests/license/compare/go-licenses, e2e-tests/license/compare/golicense, go.mod, go.sum, internal/controller/postgrescluster/instance.go, internal/controller/postgrescluster/pgadmin.go, internal/controller/postgrescluster/pgbackrest.go, internal/controller/postgrescluster/util.go, internal/controller/postgrescluster/util_test.go, internal/naming/labels.go
[![K8SPG-435](https://badgen.net/badge/JIRA/K8SPG-435/green)](https://jira.percona.com/browse/K8SPG-435) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* vmagent stores tmp data in tmp dir and maximum size can be
1G. We need to increase the size of this dir.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-435 maximum size of tmp data can be 1G

e2e-tests/functions, e2e-tests/vars.sh
[![CLOUD-808](https://badgen.net/badge/JIRA/CLOUD-808/green)](https://jira.percona.com/browse/CLOUD-808) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
- Combine IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG parameters in Jenkins pipelines into one IMAGE_PMM_SERVER (it's just excessive copy pasting, all the other images we have only one parameter for both)
- Rename IMAGE_PMM to IMAGE_PMM_CLIENT
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-808 Fix PMM server deployment in tests

e2e-tests/tests/monitoring/01-assert.yaml, e2e-tests/tests/monitoring/03-assert.yaml, e2e-tests/vars.sh
[![CLOUD-812](https://badgen.net/badge/JIRA/CLOUD-812/green)](https://jira.percona.com/browse/CLOUD-812) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
`monitoring` test case was failing
**Cause:** & **Solution:**
- The assert yaml file for the install-PMM-server step has to be updated
- The timeout of the create-cluster assert step has to be increased, too, because it didn't wait long enough for the PG cluster to be created and was failing prematurely.
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-812 Fix monitoring test case for PG operator which fails due to assert for PMM server creation

internal/controller/postgrescluster/cluster.go, internal/controller/postgrescluster/cluster_test.go, internal/controller/postgrescluster/instance.go, internal/controller/postgrescluster/patroni.go, internal/controller/postgrescluster/patroni_test.go, internal/controller/postgrescluster/pgadmin.go, internal/controller/postgrescluster/pgadmin_test.go, internal/controller/postgrescluster/pgbackrest.go, internal/controller/postgrescluster/pgbackrest_test.go, internal/controller/postgrescluster/pgbouncer.go, internal/controller/postgrescluster/pgbouncer_test.go, internal/controller/postgrescluster/pki.go, internal/controller/postgrescluster/postgres.go, internal/controller/postgrescluster/postgres_test.go, internal/controller/postgrescluster/volumes.go, internal/controller/postgrescluster/volumes_test.go, internal/naming/labels.go, internal/naming/labels_test.go, internal/pgbackrest/config.go, internal/pgbackrest/config_test.go, pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-430](https://badgen.net/badge/JIRA/K8SPG-430/green)](https://jira.percona.com/browse/K8SPG-430) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
New labels were added on older versions of the operator which should not be the case.
**Solution:**
Add labels only to 2.3.0 and above.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-430: Add labels only for 2.3.0 and above

e2e-tests/functions
[![K8SPG-467](https://badgen.net/badge/JIRA/K8SPG-467/green)](https://jira.percona.com/browse/K8SPG-467) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
```
+ diff -u /Users/plavi/Development/percona/kubernetes/percona/percona-postgresql-operator-v1/e2e-tests/affinity/compare/job_backrest-backup-some-name.yml /var/folders/fw/lxhtthdn7d9610w5p3wb33340000gn/T/tmp.XZOwxeWSUi/job_backrest-backup-some-name.yml
--- /Users/plavi/Development/percona/kubernetes/percona/percona-postgresql-operator-v1/e2e-tests/affinity/compare/job_backrest-backup-some-name.y …
```
=> K8SPG-467 - Fix job diff for newer k8s

e2e-tests/affinity/compare/job_backrest-backup-some-name-required.yml, e2e-tests/affinity/compare/job_backrest-backup-some-name.yml, e2e-tests/affinity/run, installers/ansible/roles/pgo-operator/files/pgo-configs/pod-anti-affinity.json, internal/operator/backrest/backup.go, pkg/apis/crunchydata.com/v1/cluster.go
[![K8SPG-464](https://badgen.net/badge/JIRA/K8SPG-464/green)](https://jira.percona.com/browse/K8SPG-464) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Backups are stuck because of anti affinity configuration.
**Cause:**
Backup pods configures anti affinity with postgres labels rather than pgbackrest labels.
**Solution:**
Configure backup job anti affinity with correct labels.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-464: Fix unscheduled backups if anti affinity is required

internal/controller/postgrescluster/postgres.go
[![K8SPG-472](https://badgen.net/badge/JIRA/K8SPG-472/green)](https://jira.percona.com/browse/K8SPG-472) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Built-in extensions can't be enabled after disabling.
**Cause:**
Bug in database revision calculation prevents re-enabling.
**Solution:**
Squash the bug.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-472: Fix re-enabling built-in extensions after disabling

e2e-tests/vars.sh
[![K8SPG-486](https://badgen.net/badge/JIRA/K8SPG-486/green)](https://jira.percona.com/browse/K8SPG-486) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-486 The IMAGE_EXT_INSTALLER variable was using wrong image

e2e-tests/tests/migration-backup-s3/05-run-v1-s3-backup.yaml, e2e-tests/tests/scheduled-backup/08-assert.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-358]: https://perconadev.atlassian.net/browse/K8SPG-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> K8SPG-358 Update timeout value in 08-assert.yaml of scheduled-backup test case

e2e-tests/tests/scheduled-backup/07-add-more-data.yaml, e2e-tests/tests/scheduled-backup/08-assert.yaml, e2e-tests/tests/scheduled-backup/10-add-more-data.yaml
---
*scheduled-backup test was failing sporadically because WAL was not archived each time.*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-358]: https://perconadev.atlassian.net/browse/K8SPG-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-358 - Fix scheduled-backup test for OpenShift and EKS

deploy/bundle.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
[![K8SPG-497](https://badgen.net/badge/JIRA/K8SPG-497/green)](https://jira.percona.com/browse/K8SPG-497) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
*Update versions for `2.3.1` release*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-497]: https://perconadev.atlassian.net/browse/K8SPG-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-497 - Update versions for 2.3.1 release

percona/controller/pgcluster/controller.go, percona/controller/pgcluster/schedule.go
[![K8SPG-493](https://badgen.net/badge/JIRA/K8SPG-493/green)](https://jira.percona.com/browse/K8SPG-493) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-493
---
**Problem:**
*When `.spec.pause` is set to true in `PerconaPGCluster`, operator creates scheduled backup*
**Solution:**
*Check if the cluster is paused before trying to create the scheduled backup.*
Also, this PR reduces the chances of `pg-backup` stuck in `Starting` state, which is caused by crunchy reconcile not triggered by `pg-backup` update. This is done by …
=> K8SPG-493: disable scheduled backups when `.spec.pause: true`

README.md
[![CLOUD-820](https://badgen.net/badge/JIRA/CLOUD-820/green)](https://jira.percona.com/browse/CLOUD-820) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
modified:   README.md
---
**Problem:** 
READMEs across all Operators are misaligned, having different structure, content and lacking links to Documentation
*Short explanation of the problem.* 
Update README to mention documentation
**Cause:**
**Solution:**
Added Docs links, updated READMe structure and content
*Short explanation of the solution we …
=> CLOUD-820 README update to mention documentation

percona/controller/pgbackup/controller.go
[![K8SPG-535](https://badgen.net/badge/JIRA/K8SPG-535/green)](https://jira.percona.com/browse/K8SPG-535) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
If you try to perform a backup with a repo not defined in the spec, the operator panics.
**Solution:**
Handle missing repo properly.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-535]: https://perconadev.atlassian.net/browse/K8SPG-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-535: Panic on missing repo

Makefile
[![K8SPG-583](https://badgen.net/badge/JIRA/K8SPG-583/green)](https://jira.percona.com/browse/K8SPG-583) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*We were not setting the current version for releases in pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go*
**Solution:**
*Update the Makefile `release` and `after-release` targets*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-583]: https://perconadev.atlassian.net/browse/K8SPG-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
=> K8SPG-583 - Fix release version update in Makefile

percona/controller/pgcluster/version.go, pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-583](https://badgen.net/badge/JIRA/K8SPG-583/green)](https://jira.percona.com/browse/K8SPG-583) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
When setting `version.Meta` we set the hardcoded `v2.Version` operator version. We need to set `cr.Spec.CRVersion`.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-583]: https://perconadev.atlassian.net/browse/K8SPG-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-583: Set correct operator version for version meta

Jenkinsfile
[![CLOUD-850](https://badgen.net/badge/JIRA/CLOUD-850/green)](https://jira.percona.com/browse/CLOUD-850) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
New version of `kuttl` is out and it has some improvements so it would be good to update it.
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-850]: https://perconadev.atlassian.net/browse/CLOUD-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLOUD-850 - Update kuttl version to 0.16.0

deploy/cr.yaml
[![K8SPG-514](https://badgen.net/badge/JIRA/K8SPG-514/green)](https://jira.percona.com/browse/K8SPG-514) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*The example for sysctls in cr.yaml is wrong.*
**Solution:**
*Fix it as in: https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#setting-sysctls-for-a-pod*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-514]: https://perconadev.atlassian.net/browse/K8SPG-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-514 - Fix example for sysctls in cr.yaml

deploy/cr.yaml
[![K8SPG-492](https://badgen.net/badge/JIRA/K8SPG-492/green)](https://jira.percona.com/browse/K8SPG-492) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Indentation was wrong.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-492]: https://perconadev.atlassian.net/browse/K8SPG-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-492: Fix restore indentation in default cr.yaml

e2e-tests/tests/pitr/07-assert.yaml, e2e-tests/tests/pitr/07-create-backup.yaml, e2e-tests/tests/pitr/08-ensure-latest-restorable-time-doesnt-exist.yaml, percona/controller/pgbackup/controller.go, percona/pgbackrest/pgbackrest.go, percona/watcher/wal.go
[![K8SPG-518](https://badgen.net/badge/JIRA/K8SPG-518/green)](https://jira.percona.com/browse/K8SPG-518) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We were setting latest restorable time to backup even though there are no new transactions committed to database.
**Solution:**
Check if latest restorable time is earlier than backup start timestamp and don't set it to backup if it's.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-518]: https://perconadev.atlassian.net/browse/K8SPG-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> K8SPG-518: Don't set latest restorable time if it's earlier than backup start

build/crd/percona/generated/pgv2.percona.com_perconapgclusters.yaml, config/crd/bases/pgv2.percona.com_perconapgclusters.yaml, deploy/bundle.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-595](https://badgen.net/badge/JIRA/K8SPG-595/green)](https://jira.percona.com/browse/K8SPG-595) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-595
---
This PR sets `.spec.extensions.image` field as required
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-595]: https://perconadev.atlassian.net/browse/K8SPG-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-595: set `.spec.extensions.image` field as required

config/rbac/cluster/role.yaml, config/rbac/namespace/role.yaml, deploy/bundle.yaml, deploy/cw-bundle.yaml, deploy/cw-rbac.yaml, deploy/rbac.yaml, internal/controller/postgrescluster/controller.go, percona/controller/pgbackup/controller.go, percona/controller/pgcluster/backup.go, percona/controller/pgcluster/controller.go, percona/controller/pgcluster/controller_test.go, percona/naming/annotations.go, pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
https://perconadev.atlassian.net/browse/K8SPG-600
---
**Problem:**
*If the user has the wrong `pgbackrest` credentials, the failed backup doesn't get the `failed` state in the `pg-backup` `.status.`*.
**Reason:**
*When incorrect `pgbackrest` credentials are used, the pg cluster reconcile fails, which stops the process of updating crunchy's `postgrescluster` resource. It is necessary to delete backup annotations from crunchy's resource, and this problem doesn't allow it to continue.*
**Solution:**
*Don't stop the reconcile process with the `pgbackrest` error. Log the error message instead. Also, the operator should avoid trying to use `pgbackrest` when the backup job has failed.*
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-600: Fix failed backup status

e2e-tests/tests/upgrade-minor/01-create-cluster.yaml, e2e-tests/tests/upgrade-minor/05-upgrade-cluster.yaml
[![K8SPG-597](https://badgen.net/badge/JIRA/K8SPG-597/green)](https://jira.percona.com/browse/K8SPG-597) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The test case upgrade-minor fails when the `PGO_POSTGRES_IMAGE` contains an image with minor version, e.g. `percona/percona-postgresql-operator:2.4.0-ppg16.3-postgres`. Now I use the `PG_VER` env var.
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPG-597 Fixing test case upgrade-minor to work with postures images which have minor numbers in the image name

e2e-tests/tests/monitoring/04-assert.yaml
[![K8SPG-597](https://badgen.net/badge/JIRA/K8SPG-597/green)](https://jira.percona.com/browse/K8SPG-597) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*In one position in the test we were checking for Pod status conditions (array) and Kubernetes 1.29 adds a new status `PodReadyToStartContainers`. Unfortunately `kuttl` cannot compare arrays of different sizes so the test fails on 1.29. On the other hand I don't think checking for these status conditions in this place tests anything since any pod running will have all these conditions True.* …
=> K8SPG-597 - Update monitoring test

config/rbac/cluster/role.yaml, config/rbac/namespace/role.yaml, deploy/bundle.yaml, deploy/cw-bundle.yaml, deploy/cw-rbac.yaml, deploy/rbac.yaml, percona/controller/pgupgrade/controller.go
[![K8SPG-254](https://badgen.net/badge/JIRA/K8SPG-254/green)](https://jira.percona.com/browse/K8SPG-254) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
```
create PGUpgrade: pgupgrades.postgres-operator.crunchydata.com "12-to-13" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```
**Cause:**
Operator needs to permission to upgrade `PerconaPGUpgrade` finalizers.
**Solution:**
Add permission.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-254]: …
=> K8SPG-254: Fix major upgrade on Openshift

e2e-tests/functions, e2e-tests/run-minikube.csv, e2e-tests/run-pr.csv, e2e-tests/run-release.csv, e2e-tests/tests/demand-backup/01-create-cluster.yaml, e2e-tests/tests/finalizers/00-assert.yaml, e2e-tests/tests/finalizers/00-deploy-operator.yaml, e2e-tests/tests/finalizers/01-assert.yaml, e2e-tests/tests/finalizers/01-create-cluster.yaml, e2e-tests/tests/finalizers/02-delete-cluster.yaml, e2e-tests/tests/finalizers/03-assert.yaml, e2e-tests/tests/finalizers/03-create-cluster.yaml, e2e-tests/tests/finalizers/99-remove-cluster-gracefully.yaml, e2e-tests/tests/pitr/01-create-cluster.yaml, e2e-tests/tests/scheduled-backup/01-create-cluster.yaml, e2e-tests/tests/start-from-backup/01-create-cluster.yaml, e2e-tests/tests/tablespaces/01-create-cluster.yaml, e2e-tests/tests/users/01-create-cluster.yaml, percona/controller/pgcluster/finalizer.go
[![K8SPG-616](https://badgen.net/badge/JIRA/K8SPG-616/green)](https://jira.percona.com/browse/K8SPG-616) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
For some reason `percona.com/stop-watchers` finalizer runs twice and in the second run it tries to send data to a channel no one reads from and this makes operator stuck. **This is a sporadic issue.**
**Solution:**
Ensure operator is not stuck even if it tries to send to channel with no readers.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-616]: …
=> K8SPG-616: Fix stuck operator after cluster deletion

e2e-tests/tests/scheduled-backup/01-assert.yaml, e2e-tests/tests/scheduled-backup/06-assert.yaml, e2e-tests/tests/scheduled-backup/06-engage-gcs.yaml, e2e-tests/tests/scheduled-backup/07-assert.yaml, e2e-tests/tests/scheduled-backup/07-engage-azure.yaml, e2e-tests/tests/scheduled-backup/08-assert.yaml
[![K8SPG-604](https://badgen.net/badge/JIRA/K8SPG-604/green)](https://jira.percona.com/browse/K8SPG-604) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
assert-10.yaml test is failing due to too big generation.
**Cause:**
On tests 6 and 7 backup is made too long so a couple of azure/gcp backups is scheduled instead of 1 while Success status and required Generation are waited. As a result on step 10 Generation is bigger than expected because more backups were made.
**Solution:**
Check PostgresCluster Generation and Success status of Backups only on …
=> K8SPG-604: fix scheduled backup

deploy/cr.yaml
[![K8SPG-631](https://badgen.net/badge/JIRA/K8SPG-631/green)](https://jira.percona.com/browse/K8SPG-631) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The `dataSource.postgresCluster.clusterNamespace` CR option mentioned in K8SPG-631 ticket is usable but not present in deploy/cr.yaml
**Solution:**
Update deploy/cr.yaml to follow the documentation update
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-631]: https://perconadev.atlassian.net/browse/K8SPG-631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
=> K8SPG-631 Add cross-namespace cluster restore example

deploy/cr.yaml
[![K8SPG-244](https://badgen.net/badge/JIRA/K8SPG-244/green)](https://jira.percona.com/browse/K8SPG-244) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
`spec.instances[].dataVolumeClaimSpec.resources.limits.storage` option needed to use storage autoresize wasn't present in deploy/cr.yaml
**Solution:**
Update deploy/cr.yaml to follow the documentation update
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-244]: https://perconadev.atlassian.net/browse/K8SPG-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> K8SPG-244 Add storage limit example to cr.yaml

go.mod, go.sum
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-727 bump golang.org/x/net to 0.33.0

percona/controller/pgcluster/controller.go
[![K8SPG-692](https://badgen.net/badge/JIRA/K8SPG-692/green)](https://jira.percona.com/browse/K8SPG-692) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-692
---
In this PR, the `*-patroni-version-check` pod gets `resources` and `securityContext` from `.spec.instances[0]`. This should be fine as the pod is created and deleted before the pg pods are deployed.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-692]: https://perconadev.atlassian.net/browse/K8SPG-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> K8SPG-692: set `resources` & `securityConext` for patroni version check

e2e-tests/tests/demand-backup/01-create-cluster.yaml, e2e-tests/tests/demand-backup/04-assert.yaml, internal/controller/postgrescluster/pgbackrest.go
[![K8SPG-619](https://badgen.net/badge/JIRA/K8SPG-619/green)](https://jira.percona.com/browse/K8SPG-619) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-619
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-619]: https://perconadev.atlassian.net/browse/K8SPG-619?atlOrigin=eyJpIjoiNWRkNTlj …
=> K8SPG-619: fix applying `backoffLimit` for backup jobs

internal/controller/postgrescluster/delete.go, percona/controller/pgbackup/controller.go, percona/controller/pgcluster/controller.go, pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-713](https://badgen.net/badge/JIRA/K8SPG-713/green)](https://jira.percona.com/browse/K8SPG-713) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-713
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-713]: https://perconadev.atlassian.net/browse/K8SPG-713?atlOrigin=eyJpIjoiNWRkNTlj …
=> K8SPG-713: handle errors on pgcluster deletion

percona/controller/pgcluster/finalizer.go
[![K8SPG-586](https://badgen.net/badge/JIRA/K8SPG-586/green)](https://jira.percona.com/browse/K8SPG-586) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The finalizer deletes all pg-backup objects from all the clusters in the namespace.
**Solution:**
Delete pg-objects only for the corresponding PG cluster
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-586]: https://perconadev.atlassian.net/browse/K8SPG-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-586: Delete pg-objects only for the corresponding PG cluster

.github/workflows/test.yml, internal/controller/postgrescluster/pgbackrest_test.go, internal/controller/postgrescluster/snapshots_test.go, percona/controller/pgbackup/controller.go, percona/controller/pgcluster/controller.go, percona/controller/utils.go, percona/postgres/common.go
https://perconadev.atlassian.net/browse/K8SPG-714
---
This PR fixes the panic on update to 2.6.0 operator
Also it fixes following issues:
- handles conflict error on `pgbackup` status update, which caused following log message: `update PGBackup status: Operation cannot be fulfilled on perconapgbackups.pgv2.percona.com \"XXX\": the object has been modified`
- resources not being applied to `patroni-version-check` pod
- reduces `patroni-version-check` pod's `terminationGracePeriod` to 5
- fixes `percona.com/delete-backup` not being removed after backup completion 
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPG-714: fix panic

e2e-tests/tests/finalizers/01-assert.yaml, e2e-tests/tests/finalizers/03-assert.yaml, percona/controller/pgcluster/controller.go, percona/naming/finalizers.go, percona/naming/prefix.go
[![K8SPG-637](https://badgen.net/badge/JIRA/K8SPG-637/green)](https://jira.percona.com/browse/K8SPG-637) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-637
---
This PR adds an `internal.` prefix to finalizers that are used only by the operator and are not intended for user use:
- `percona.com/stop-watchers` => `internal.percona.com/stop-watchers`
- `percona.com/delete-backup` => `internal.percona.com/delete-backup`
- `percona.com/delete-restore` => `internal.percona.com/delete-restore`
The change from …
=> K8SPG-637: add `internal.` prefix to operator finalizers

e2e-tests/tests/migration-backup-s3/09-deploy-cluster.yaml
[![K8SPG-651](https://badgen.net/badge/JIRA/K8SPG-651/green)](https://jira.percona.com/browse/K8SPG-651) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
migration-backup-s3 test fails on step 09 because it takes more than 5 sec for `migration-backup-s3-pgbackrest-restore` job to be created.  As a result when we run `kubectl -n $NAMESPACE wait --for=condition=Complete` there is no object and test fails.
**Solution:**
Wait for longer time before checking restore job completion,
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPG-651: wait longer for migration-backup-s3-pgbackrest-restore

e2e-tests/tests/demand-backup/25-delete-cluster-with-finalizer.yaml
[![K8SPG-651](https://badgen.net/badge/JIRA/K8SPG-651/green)](https://jira.percona.com/browse/K8SPG-651) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
It takes longer than default 180 sec timeout to delete cluster and execute all the finalizers. As a result test fails due to timeout exceeded.
**Solution:**
Increase timeout for delete-cluster-with-finalizer step to 360 sec.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-651]: https://perconadev.atlassian.net/browse/K8SPG-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
=> K8SPG-651: increase timeout for demand-backup cluster deletion

Jenkinsfile, e2e-tests/functions, e2e-tests/tests/monitoring/06-check-pgstatstatements-query-source.yaml
[![K8SPG-651](https://badgen.net/badge/JIRA/K8SPG-651/green)](https://jira.percona.com/browse/K8SPG-651) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Monitoring test fails because the metrics are not present yet in PMM when we try to retrieve them.
**Cause:**
**Solution:**
Add retry to wait till first metrics are inserted.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-651]: https://perconadev.atlassian.net/browse/K8SPG-651?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> K8SPG-651: add retry for qan mentics and increase timeout for st6

deploy/cr.yaml, percona/controller/pgcluster/controller.go, percona/controller/pgcluster/testutils_test.go, percona/naming/annotations.go
[![K8SPG-648](https://badgen.net/badge/JIRA/K8SPG-648/green)](https://jira.percona.com/browse/K8SPG-648) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-648
---
**Problem:**
*`patroni-version-check` is created multiple times on startup, when it should be created only once.*
**Cause:**
*Instance pods don't have `imageID`'s on startup. Operator can't find the previous `imageID` in the empty slice of pod's `imageID`'s and creates new version check.*
**Solution:**
*Add a check for an empty `imageID` slice.*
This PR adds the …
=> K8SPG-648: fix `patroni-version-check` behaviour on startup

build/crd/percona/generated/pgv2.percona.com_perconapgclusters.yaml, config/crd/bases/pgv2.percona.com_perconapgclusters.yaml, deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, e2e-tests/functions, e2e-tests/tests/monitoring-pmm3/03-assert.yaml, e2e-tests/tests/monitoring/03-assert.yaml, percona/pmm/pmm.go, percona/pmm/pmm_test.go, pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go
[![K8SPG-654](https://badgen.net/badge/JIRA/K8SPG-654/green)](https://jira.percona.com/browse/K8SPG-654) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Allow to add custom params to pmm section 
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-654]: https://perconadev.atlassian.net/browse/K8SPG-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-654 add possibility of adding custom postgres params for PMM

build/postgres-operator/Dockerfile, cmd/postgres-operator/main.go
[![K8SPG-738](https://badgen.net/badge/JIRA/K8SPG-738/green)](https://jira.percona.com/browse/K8SPG-738) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
```
$ k logs percona-postgresql-operator-86f7cf59cd-5hs7w
2025-03-26T14:54:22.654Z        INFO    Manager starting up     {"gitCommit": "72f3dc3c1b12063e3260fc1799e3e240ffb67ab1", "gitBranch": "K8SPG-738", "buildTime": "2025-03-26T14:52:43Z", "goVersion": "go1.23.7", "os": "linux", "arch": "amd64"}
...
```
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-738]: …
=> K8SPG-738: Add startup log to print commit hash, branch and build time

build/crd/percona/generated/pgv2.percona.com_perconapgclusters.yaml, config/crd/bases/pgv2.percona.com_perconapgclusters.yaml, deploy/bundle.yaml, deploy/crd.yaml, deploy/cw-bundle.yaml, e2e-tests/tests/monitoring-pmm3/06-check-pgstatstatements-query-source.yaml, e2e-tests/tests/monitoring/06-check-pgstatstatements-query-source.yaml, pkg/apis/pgv2.percona.com/v2/perconapgcluster_types.go, pkg/apis/pgv2.percona.com/v2/zz_generated.deepcopy.go
[![K8SPG-753](https://badgen.net/badge/JIRA/K8SPG-753/green)](https://jira.percona.com/browse/K8SPG-753) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Add an explicit field to control `pg_stat_statements` extension.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-753]: https://perconadev.atlassian.net/browse/K8SPG-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPG-753: Add field to control pg_stat_statements

cmd/postgres-operator/main.go, cmd/postgres-operator/main_test.go, config/manager/default/manager.yaml, deploy/bundle.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml, percona/controller/pgcluster/controller_test.go, percona/runtime/runtime.go
[![K8SPG-761](https://badgen.net/badge/JIRA/K8SPG-761/green)](https://jira.percona.com/browse/K8SPG-761) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-761
---
This PR adds support for the `PGO_WORKERS` environment variable in the operator. It allows to configure the number of concurrent reconciliations for the `postgres-operator.crunchydata.com/v1beta1` `PostgresCluster` resource.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-761]: https://perconadev.atlassian.net/browse/K8SPG-761?atlOrigin=eyJpI …
=> K8SPG-761: add support for the `PGO_WORKERS` env var

Jenkinsfile, e2e-tests/functions, e2e-tests/release_versions, e2e-tests/tests/monitoring-pmm3/03-create-cluster.yaml, e2e-tests/vars.sh
[![K8SPG-719](https://badgen.net/badge/JIRA/K8SPG-719/green)](https://jira.percona.com/browse/K8SPG-719) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
With the image and tag misconfigured, they are ignored, and instead, we are always using by default the latest released version.
**Cause:**
**Solution:**
based on this: https://github.com/percona/percona-helm-charts/tree/main/charts/pmm#percona-monitoring-and-management-pmm-parameters
**CHECKLIST**
---
**Jira**
**Tests** …
=> K8SPG-719 use image.tag and image.repository to configure pmm3 server on e2e tests

.e2eignore, .snyk
[![CLOUD-911](https://badgen.net/badge/JIRA/CLOUD-911/green)](https://jira.percona.com/browse/CLOUD-911) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Add .snyk file to ignore e2e-tests directory in scans.
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-911]: https://perconadev.atlassian.net/browse/CLOUD-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CLOUD-911: Add snyk config

deploy/cr.yaml
[![K8SPG-613](https://badgen.net/badge/JIRA/K8SPG-613/green)](https://jira.percona.com/browse/K8SPG-613) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPG-613
---
The previous PR (https://github.com/percona/percona-postgresql-operator/pull/1117) introduced an incorrect `containerSecurityContext` that does not match the `crd.yaml`
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPG-613]: https://perconadev.atlassian.net/browse/K8SPG-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> K8SPG-613: fix cr.yaml

percona/pmm/pmm.go, percona/pmm/pmm_test.go
[![K8SPG-826](https://badgen.net/badge/JIRA/K8SPG-826/green)](https://jira.percona.com/browse/K8SPG-826) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The pmm-client container on PMM3 uses the /tmp directory, but on OpenShift, this directory will be overwritten by PMM3 when pods restart, leading to potential data loss or issues with metric collection.
This PR updates the configuration to use a different temporary directory for pmm-client regardless of platform, ensuring data safety across pod restarts.
**Cause:**
*Short explanation of the root …
=> K8SPG-826 use /tmp/pmm for pmm3 env var PMM_AGENT_PATHS_TEMPDIR

internal/controller/postgrescluster/postgres.go
[![K8SPG-570](https://badgen.net/badge/JIRA/K8SPG-570/green)](https://jira.percona.com/browse/K8SPG-570) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
If a `secretName` is not specified when configuring a user through cr but a secret with a valid user password is created for that user using the default secret name that the operator is using for creating secrets itself, the secret should be identified as existing and honor the password that it configures.
e.g.
for secret name `<cluster>-pguser-<username>`, after applying the CR, the existing …
=> K8SPG-570 treat user-created secrets with operator default secret name as custom
